# Generated by Django 5.2.5 on 2025-08-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'permissions': (('can_edit_article', 'Can edit article'), ('can_delete_article', 'Can delete article')),
            },
        ),
    ]
